### ISSUE TITLE
Feature: mark the menu item as checked

### ISSUE THREAD

**Issue by egoist** [c2r0b/tauri-plugin-context-menu#10]
Would be useful to implement a radio group like this:

![CleanShot 2023-10-24 at 02 58 28@2x](https://github.com/c2r0b/tauri-plugin-context-menu/assets/8784712/0851b8b3-06a3-4426-84d6-e6c18b4c62bb)

**Comment by c2r0b** [comment]
Added in v0.7.0 (#20)

````js
items: [
  ...
  {
    ...
    checked: true
    ...
  }
]
````
