### ISSUE TITLE
BUG: [Linux] context menu is closed immediately

### ISSUE THREAD

**Issue by wyhaya** [c2r0b/tauri-plugin-context-menu#16]
https://github.com/c2r0b/tauri-plugin-context-menu/assets/23690145/1bed0423-c348-49be-bc73-4c7f0f31fd30

There is nothing wrong with the JS events, everything is the expected behavior, this error doesn't happen every time, but it occurs quite frequently.

There is also a GTK warning, which I'm not sure is relevant:

```
No trigger event for menu popup
```

System: `Fedora 39`

**Comment by c2r0b** [comment]
Seems like changing the interval [here](https://github.com/c2r0b/tauri-plugin-context-menu/blob/ad0e52927834a2e87fefa2fb8f74a148f74c9052/src/lib.rs#L144) has some effect on that.
It appears to me to be some kind of issue with the gtk components lifecycle.  

I will try to look into it, but a PR is welcome
