### ISSUE TITLE
[feat] Support for dynamic themes

### ISSUE THREAD

**Issue by ayangweb** [c2r0b/tauri-plugin-context-menu#25]
Hey, thanks for such a great plugin, I'm currently using [tauri-plugin-theme](https://github.com/wyhaya/tauri-plugin-theme) for dynamic theme switching, is it possible to provide a `theme` parameter to dynamically change the theme color of the menu?

**Comment by c2r0b** [comment]
Yes, that should be doable. I am going to work on it

**Comment by ayangweb** [comment]
> Yes, that should be doable. I am going to work on it

Thank you, it's really great and I'm already looking forward to it!

**Comment by c2r0b** [comment]
The themes implementation for macOS should work now in the `dev` branch.
I am trying to find a way to support Linux and Windows too.

To try out the macOS version you can import the plugin like this: 
````
tauri-plugin-context-menu = { git = "https://github.com/c2r0b/tauri-plugin-context-menu", branch = "dev" }
````

You can then pass the option `theme` that is either `light` or `dark` to the plugin (updated docs [here](https://github.com/c2r0b/tauri-plugin-context-menu/tree/dev?tab=readme-ov-file#options)).

**Comment by ayangweb** [comment]
> The themes implementation for macOS should work now in the `dev` branch. I am trying to find a way to support Linux and Windows too.
> 
> To try out the macOS version you can import the plugin like this:
> 
> ```
> tauri-plugin-context-menu = { git = "https://github.com/c2r0b/tauri-plugin-context-menu", branch = "dev" }
> ```
> 
> You can then pass the option `theme` that is either `light` or `dark` to the plugin (updated docs [here](https://github.com/c2r0b/tauri-plugin-context-menu/tree/dev?tab=readme-ov-file#options)).

Okay, thanks, that's really great!

**Comment by ayangweb** [comment]
> The themes implementation for macOS should work now in the `dev` branch. I am trying to find a way to support Linux and Windows too.
> 
> To try out the macOS version you can import the plugin like this:
> 
> ```
> tauri-plugin-context-menu = { git = "https://github.com/c2r0b/tauri-plugin-context-menu", branch = "dev" }
> ```
> 
> You can then pass the option `theme` that is either `light` or `dark` to the plugin (updated docs [here](https://github.com/c2r0b/tauri-plugin-context-menu/tree/dev?tab=readme-ov-file#options)).

Works fine on MacOS 🥰

**Comment by c2r0b** [comment]
I went ahead and published v0.8 with MacOS theme option support.

Unfortunately, both Windows and Linux (Gtk) do not seem to have a way to handle theme changes for a single widget 😓
Instead, they always fall back to the global window theme.

`tauri-plugin-theme` changes the window theme, therefore it should change the menu theme automatically (on Windows and Linux).
Please let me know if you have time to confirm this.

**Comment by ayangweb** [comment]
> I went ahead and published v0.8 with MacOS theme option support.
> 
> Unfortunately, both Windows and Linux (Gtk) do not seem to have a way to handle theme changes for a single widget 😓 Instead, they always fall back to the global window theme.
> 
> `tauri-plugin-theme` changes the window theme, therefore it should change the menu theme automatically (on Windows and Linux). Please let me know if you have time to confirm this.

Windows：
<img width="1063" alt="image" src="https://github.com/user-attachments/assets/76a2c578-f54b-4813-a4f3-cf379e29b957">

Windows tests are not following the window theme, and Linux I don't have a test machine at the moment!

**Comment by c2r0b** [comment]
Thank you for the test.
I am going to look into the Windows issue and update this thread

**Comment by ayangweb** [comment]
> Thank you for the test. I am going to look into the Windows issue and update this thread

Well, thank you! 😁

**Comment by c2r0b** [comment]
I made some tests, but I could not figure out how to make Windows context menu appearance light or dark on demand (tried on Windows 10).

Help is wanted on this 🙏

**Comment by ayangweb** [comment]
> I made some tests, but I could not figure out how to make Windows context menu appearance light or dark on demand (tried on Windows 10).
> 
> Help is wanted on this 🙏

Maybe tauri v1 really doesn't have a way to implement dynamic themes in windows!

v2：https://github.com/wyhaya/tauri-plugin-theme/issues/5#issuecomment-2346711846

linux：Let's see if this helps. https://github.com/wyhaya/tauri-plugin-theme/blob/main/src/platform/linux.rs
