### ISSUE TITLE
Feature: support for different context menus dependending on where its opened

### ISSUE THREAD

**Issue by kyteidev** [c2r0b/tauri-plugin-context-menu#27]
Hi

This plugin works great, but my app requires different context menus when I right click in different areas. Is that possible to implement?

I have tried adding the event listener directly to the element, but custom context menus wouldn't show up :(

**Comment by c2r0b** [comment]
It is indeed possible to have multiple context menus by attaching the event listeners to various DOM elements.

I just added an example to showcase that [here](https://github.com/c2r0b/tauri-plugin-context-menu/blob/main/examples/multi/public/index.js).

After cloning this repository, you can also try running the example:
`````
npm run examples/multi
`````

If this doesn't help, please send a reproducible example of your problem.
