### ISSUE TITLE
Menu position is wrong in the second display

### ISSUE THREAD

**Issue by jiakuan** [c2r0b/tauri-plugin-context-menu#28]
I use a second display connecting to my MacBook Pro. The context menu works fine in the main display (the MacBook one), but the menu position is outside of the app in the second display.

Any ideas?

**Comment by c2r0b** [comment]
Fix released in [v0.8.1](https://crates.io/crates/tauri-plugin-context-menu/0.8.1)

Thank you for reaching out

**Comment by c2r0b** [comment]
Can you try running an example of this repository and see if it behaves the same way? (Instructions [here](https://github.com/c2r0b/tauri-plugin-context-menu?tab=readme-ov-file#examples))

Also, please provide these info that might be helpful while investigating the isssue:
- which resolution is set for your displays?
- what are you passing as position options? (Meaning [this](https://github.com/c2r0b/tauri-plugin-context-menu?tab=readme-ov-file#options))

**Comment by jiakuan** [comment]
I tried the `examples/vanilla` and got the same behaviour on the extended display:
<img width="538" alt="Screenshot 2024-08-29 at 09 10 50" src="https://github.com/user-attachments/assets/45d45d48-1479-4a90-b9a8-66d32547e283">
I right clicked at the end of the word "anywhere", but the menu was shown way down below at the bottom.

My main display is `PHL 328B1` with a resolution of `3008 x 1692`, and my extended display is the MacBook Pro built-in display, which has a resolution of `1680 x 1050`. And they are arranged side by side. Please see screenshots below.
<img width="500" alt="Screenshot 2024-08-29 at 09 09 42" src="https://github.com/user-attachments/assets/27a8904f-2ac5-44e1-a8ce-eaee474907cb">
<img width="501" alt="Screenshot 2024-08-29 at 09 09 56" src="https://github.com/user-attachments/assets/62097aa7-9f2b-4daa-b802-d9472c0dbcaf">
<img width="606" alt="Screenshot 2024-08-29 at 09 08 51" src="https://github.com/user-attachments/assets/749dd2a6-0f7e-43ca-b22e-26fe5c7c7ab0">

In terms of the position options, I passed the same as the vanilla example:

```
pos: {
    x: e.clientX,
    y: e.clientY
},
```

Just the `clientX` and `clientY` of the mouse event.

I will be happy test the fixes on a different setup as I have another display with a different laptop.

**Comment by c2r0b** [comment]
I tried replicating you settings as close as possible, using a different monitor model but same resolution settings.
In my test the menu position was correct.

- Is your issue persistent with any resolution you set?
- Can you please try with a different laptop/display?
