### ISSUE TITLE
[bug] windows open context menu unresponsive

### ISSUE THREAD

**Issue by ayangweb** [c2r0b/tauri-plugin-context-menu#29]
Hey 👋, excuse me. I'm using this plugin in [EcoPaste](https://github.com/ayangweb/EcoPaste), but I'm getting [feedback](https://github.com/ayangweb/EcoPaste/issues/288) that the context menu is unresponsive in `Windows 10`, and partially in other communities as well! After some troubleshooting, this may not be an issue with `EcoPaste`, as it is fine on both `MacOS` and `Windows 11`! Hope you guys can help me out with this, thanks 🌹!

![image](https://github.com/user-attachments/assets/3bf5dda0-6c60-4e75-b6b1-8c06b7c169f7)

**Comment by c2r0b** [comment]
Hi, the Windows version of this plugin was actually developed on a Windows 10 machine. Are you able to create a reproducible minimal example of the issue? Do you have any error shown?

This error does not seem to happen running this repository examples on Windows 10, please double check on your machine if you have time 🙏

**Comment by ayangweb** [comment]
https://github.com/EcoPasteHub/EcoPaste/issues/547

I can't reproduce it on my computer, but there is a lot of feedback on this issue!

**Comment by ayangweb** [comment]
https://github.com/EcoPasteHub/EcoPaste/blob/ad630b087651d353343df3cad88753c1dfdf2a21/src/pages/Clipboard/Panel/components/List/components/Item/index.tsx#L223 我是在这里使用插件！

**Comment by ayangweb** [comment]
Hey 👋, I've only submitted a minimal reproducible case with this plugin, the steps to reproduce it: right click to show the context menu, then go to open another app's window, and then it's unresponsive!

repository: https://github.com/ayangweb/test-tauri-plugin-context-menu

Video Demo:

https://github.com/user-attachments/assets/6fcfb81e-7826-4590-81bc-b0bb8f87f7a3

**Comment by c2r0b** [comment]
Should be fixed in [v0.8.2](https://crates.io/crates/tauri-plugin-context-menu/0.8.2)
The context menu should now correctly destroy itself when the window focus is lost
