### ISSUE TITLE
Add metadata (event payload)

### ISSUE THREAD

**Issue by cuipeiyu** [c2r0b/tauri-plugin-context-menu#3]
Great plugin !

Is there any plan to support metadata?

like:
{
    label: 'My first subitem',
    event: 'my_first_subitem',
    metadata: '{"id":123}' // any string
}

**Comment by c2r0b** [comment]
Great idea! It should be a pretty straightforward implementation.
I am busy working on Linux support so a PR is welcome, otherwise I will work on it right after v0.5

**Comment by kurdin** [comment]
@c2r0b  thanks for plugin, please add payload object that we can pass from the menu to event listener. I wish I could help but I am not rust dev.

**Comment by c2r0b** [comment]
Implemented in v0.5.0 🎉
