### ISSUE TITLE
Add Tauri V2 Support

### ISSUE THREAD

**Issue by Swivelgames** [c2r0b/tauri-plugin-context-menu#33]
I know, I know... Tauri V2 "supports" context menus built-in. But, does it?

![image](https://github.com/user-attachments/assets/ab0386f5-03de-4b92-8ef3-57a2cedaa8cb)

Not really. Especially given that most of my target audience is going to be Linux users, I would love for this to be brought back to life and updated to support Tauri V2 :tada:

**Comment by c2r0b** [comment]
Tauri v2 supports native context menu on MacOS, Windows and Linux.

That message in the documentation is badly formatted and only refers to the NativeIcon (see the original thread [here](https://github.com/tauri-apps/tauri/issues/4338#issuecomment-2420149355))
