### ISSUE TITLE
Add TypeScript API package

### ISSUE THREAD

**Issue by HuakunShen** [c2r0b/tauri-plugin-context-menu#4]
Can you add a TypeScript API wrapper? Like https://github.com/CrossCopy/tauri-plugin-clipboard/blob/main/webview-src/index.ts

**Comment by c2r0b** [comment]
The TypeScript API wrapper is now available on npm as [tauri-plugin-context-menu](https://www.npmjs.com/package/tauri-plugin-context-menu) 🎉 (#5)

Usage info in the [README](https://github.com/c2r0b/tauri-plugin-context-menu/blob/main/README.md) file. 
Source code [here](https://github.com/c2r0b/tauri-plugin-context-menu/blob/main/webview-src/index.ts).

**Comment by HuakunShen** [comment]
@c2r0b Thank you!
