### ISSUE TITLE
Bug: Listeners should be properly removed

### ISSUE THREAD

**Issue by egoist** [c2r0b/tauri-plugin-context-menu#7]
https://github.com/c2r0b/tauri-plugin-context-menu/blob/af0e1134b407ee3d5c87df326da4a8d9bedddb33/webview-src/index.ts#L24

Every time you call `showMenu` a new listener for the`event` function will be created, previous ones are not removed currently, which results in the function being called multiple times.

**Comment by c2r0b** [comment]
Fixed in version 4.0.1 of the TS Utility package ([tauri-plugin-context-menu](https://www.npmjs.com/package/tauri-plugin-context-menu)) #8.

Thank you for reporting 🙏
